### ISSUE TITLE
Features: parsing/formatting

### ISSUE THREAD

**Issue by FObersteiner** [FObersteiner/zdt#5]
## additional directives
- [x] ISO string ( `%+` )
- [x] locale-based month/day names (datetime to string) -- Linux
- [x] locale-based month/day names (datetime to string) -- Windows
- [ ] locale-based month/day names (string to datetime) -- Linux
- [ ] locale-based month/day names (string to datetime) -- Windows
- [x] abbreviated tz name `%Z`

### extended directives?
- [x] directives with modifiers ( `%:z` ) ...would probably require a parser revision - see PR #17

## Unicode
- support ?

## parser
- [x] revise state machine? [like this](https://codeberg.org/ziglings/exercises/src/branch/main/exercises/108_labeled_switch.zig) maybe... see PR #17 
- [x] ISO8601 parser revision: see #18

**Comment by FObersteiner** [comment]
see wiki /roadmap
